INSERT INTO tbl_data(id,parentid, name, colour) VALUES (1,0,'Warrior','red')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (2,0,'Wizard','green')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (3,0,'Priest','white')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (4,0,'Rogue','yellow')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (5,1,'Fighter','blue')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (6,1,'Paladin','lighblue')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (7,1,'Ranger','lighgreen')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (8,2,'Mage','grey')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (9,2,'Specialist wizard','lightgrey')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (10,3,'Cleric','red')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (11,3,'Druid','green')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (12,3,'Priest of specific mythos','white')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (13,4,'Thief','white')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (14,4,'Bard','blue')
INSERT INTO tbl_data(id,parentid, name, colour) VALUES (15,13,'Assassin','lighblue')